service: serverless-task-8

plugins:
  - serverless-offline
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USER: ${env:PG_USER}
    PG_PASSWD: ${env:PG_PASSWD}


functions:
  main:
    handler: dist/main.handler
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0018a004b49a126bf
        - sg-02ac2956ccfda2ea4
      subnetIds:
        - subnet-0ef3466aad9dd6797
        - subnet-032c6718742e2f078
        - subnet-016182e6541c2ffbd
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'